Interface error on quasi-polynomial 36
========================================

Bug reported in https://github.com/Normaliz/PyNormaliz/issues/36

>>> import PyNormaliz
>>> cube = PyNormaliz.NmzCone(vertices = [[0, 0, 0, 1], [0, 0, 1, 1], [0, 1, 0, 1], [0, 1, 1, 1], [1, 0, 0, 1], [1, 0, 1, 1], [1, 1, 0, 1], [1, 1, 1, 1]])
>>> PyNormaliz.NmzCompute(cube, "EhrhartSeries" )
True
>>> PyNormaliz.NmzResult(cube, "EhrhartQuasiPolynomial") == [[1, 3, 3, 1], 1]
True
